---
deployment:
  tasks:
    # 1. MedNex SaaS Deployment
    - /bin/cp -Rf backend/. /home/vayunexs/api.mednex.vayunexsolution.com/
    - /bin/cp -Rf frontend/dist/. /home/vayunexs/mednex.vayunexsolution.com/
    - export HOME=/home/vayunexs && cd /home/vayunexs/api.mednex.vayunexsolution.com && /home/vayunexs/nodevenv/api.mednex.vayunexsolution.com/24/bin/npm install --production

    # 2. Nex Platform Core (NPC) Deployment
    - /bin/cp -Rf npc/backend/. /home/vayunexs/api.sdk.vayunexsolution.com/
    - /bin/cp -Rf npc-admin/dist/. /home/vayunexs/sdk.vayunexsolution.com/
    - export HOME=/home/vayunexs && cd /home/vayunexs/api.sdk.vayunexsolution.com && /home/vayunexs/nodevenv/api.sdk.vayunexsolution.com/24/bin/npm install --production
